
title: TAICO - Toronto AI and Cybersecurity Organization
short_title: TAICO
email: curtis@collicutt.net
description: >-
  The Toronto Artificial Intelligence and Cybersecurity Organization
subtitle: >-
  Toronto is a hotbed of high-tech innovation. TAICO is a meetup specifically created to discuss AI, cybersecurity, and the spaces where they intersect. TAICO is also about more than just discussions; it focuses on hands-on workshops, fostering entrepreneurship, and securing our companies and ourselves. By bringing together experts, enthusiasts, and entrepreneurs, TAICO aims to create a collaborative environment where ideas can be shared, skills can be developed, and our digital future can be secured.
baseurl: ""
twitter_username: jekyllrb
github_username:  jekyll
permalink: /posts/:slug/
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-postcss-v2
  - jekyll-responsive-magick

exclude:
  - README.md
  - justfile

responsive:
  widths: [400, 800, 1200]
  format: "jpg"
  quality: 80
  verbose: true
  base_path:
    - "img/gallery"
    - "img/posts"
    - "img/slides"

  
postcss:
  cache: false

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

collections:
  notes:
    output: true